var annotated_dup =
[
    [ "ddc", "namespaceddc.html", [
      [ "reducer", "namespaceddc_1_1reducer.html", [
        [ "band", "structddc_1_1reducer_1_1band.html", "structddc_1_1reducer_1_1band" ],
        [ "bor", "structddc_1_1reducer_1_1bor.html", "structddc_1_1reducer_1_1bor" ],
        [ "bxor", "structddc_1_1reducer_1_1bxor.html", "structddc_1_1reducer_1_1bxor" ],
        [ "land", "structddc_1_1reducer_1_1land.html", "structddc_1_1reducer_1_1land" ],
        [ "lor", "structddc_1_1reducer_1_1lor.html", "structddc_1_1reducer_1_1lor" ],
        [ "max", "structddc_1_1reducer_1_1max.html", "structddc_1_1reducer_1_1max" ],
        [ "min", "structddc_1_1reducer_1_1min.html", "structddc_1_1reducer_1_1min" ],
        [ "minmax", "structddc_1_1reducer_1_1minmax.html", "structddc_1_1reducer_1_1minmax" ],
        [ "prod", "structddc_1_1reducer_1_1prod.html", "structddc_1_1reducer_1_1prod" ],
        [ "sum", "structddc_1_1reducer_1_1sum.html", "structddc_1_1reducer_1_1sum" ]
      ] ],
      [ "AlignedAllocator", "classddc_1_1AlignedAllocator.html", "classddc_1_1AlignedAllocator" ],
      [ "cartesian_prod", "namespaceddc.html#structddc_1_1cartesian__prod", null ],
      [ "cartesian_prod< ddc::DiscreteDomain< DDim1... >, ddc::DiscreteDomain< DDim2... > >", "namespaceddc.html#structddc_1_1cartesian__prod_3_01ddc_1_1DiscreteDomain_3_01DDim1_8_8_8_01_4_00_01ddc_1_1Discrete74c011d44ff586684f50f3f3d6d191c1", "namespaceddc_structddc_1_1cartesian__prod_3_01ddc_1_1DiscreteDomain_3_01DDim1_8_8_8_01_4_00_01ddc_1_1Discrete74c011d44ff586684f50f3f3d6d191c1_dup" ],
      [ "cartesian_prod< DDom >", "namespaceddc.html#structddc_1_1cartesian__prod_3_01DDom_01_4", "namespaceddc_structddc_1_1cartesian__prod_3_01DDom_01_4_dup" ],
      [ "cartesian_prod< DDom1, DDom2, Tail... >", "namespaceddc.html#structddc_1_1cartesian__prod_3_01DDom1_00_01DDom2_00_01Tail_8_8_8_01_4", "namespaceddc_structddc_1_1cartesian__prod_3_01DDom1_00_01DDom2_00_01Tail_8_8_8_01_4_dup" ],
      [ "Chunk", "namespaceddc.html#classddc_1_1Chunk", null ],
      [ "Chunk< ElementType, DiscreteDomain< DDims... >, Allocator >", "classddc_1_1Chunk_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01Allocator_01_4.html", "classddc_1_1Chunk_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01Allocator_01_4" ],
      [ "chunk_traits", "namespaceddc.html#structddc_1_1chunk__traits", "namespaceddc_structddc_1_1chunk__traits_dup" ],
      [ "ChunkCommon", "namespaceddc.html#classddc_1_1ChunkCommon", null ],
      [ "ChunkCommon< ElementType, DiscreteDomain< DDims... >, LayoutStridedPolicy >", "classddc_1_1ChunkCommon_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_01_4.html", "classddc_1_1ChunkCommon_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_01_4" ],
      [ "ChunkSpan", "namespaceddc.html#classddc_1_1ChunkSpan", null ],
      [ "ChunkSpan< ElementType, DiscreteDomain< DDims... >, LayoutStridedPolicy, MemorySpace >", "classddc_1_1ChunkSpan_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_00_01MemorySpace_01_4.html", "classddc_1_1ChunkSpan_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_00_01MemorySpace_01_4" ],
      [ "ConstantExtrapolationRule", "namespaceddc.html#structddc_1_1ConstantExtrapolationRule", null ],
      [ "ConstantExtrapolationRule< DimI >", "structddc_1_1ConstantExtrapolationRule_3_01DimI_01_4.html", "structddc_1_1ConstantExtrapolationRule_3_01DimI_01_4" ],
      [ "ConstantExtrapolationRule< DimI, DimNI >", "structddc_1_1ConstantExtrapolationRule_3_01DimI_00_01DimNI_01_4.html", "structddc_1_1ConstantExtrapolationRule_3_01DimI_00_01DimNI_01_4" ],
      [ "coordinate_of", "namespaceddc.html#structddc_1_1coordinate__of", "namespaceddc_structddc_1_1coordinate__of_dup" ],
      [ "Deriv", "namespaceddc.html#structddc_1_1Deriv", null ],
      [ "DiscreteDomain", "classddc_1_1DiscreteDomain.html", "classddc_1_1DiscreteDomain" ],
      [ "DiscreteDomain<>", "classddc_1_1DiscreteDomain_3_4.html", "classddc_1_1DiscreteDomain_3_4" ],
      [ "DiscreteDomainIterator", "structddc_1_1DiscreteDomainIterator.html", "structddc_1_1DiscreteDomainIterator" ],
      [ "DiscreteElement", "classddc_1_1DiscreteElement.html", "classddc_1_1DiscreteElement" ],
      [ "DiscreteVector", "classddc_1_1DiscreteVector.html", "classddc_1_1DiscreteVector" ],
      [ "Fourier", "namespaceddc.html#structddc_1_1Fourier", null ],
      [ "GrevilleInterpolationPoints", "classddc_1_1GrevilleInterpolationPoints.html", "classddc_1_1GrevilleInterpolationPoints" ],
      [ "is_discrete_domain", "structddc_1_1is__discrete__domain.html", null ],
      [ "is_discrete_domain< DiscreteDomain< Tags... > >", "structddc_1_1is__discrete__domain_3_01DiscreteDomain_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_discrete_element", "structddc_1_1is__discrete__element.html", null ],
      [ "is_discrete_element< DiscreteElement< Tags... > >", "structddc_1_1is__discrete__element_3_01DiscreteElement_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_discrete_vector", "structddc_1_1is__discrete__vector.html", null ],
      [ "is_discrete_vector< DiscreteVector< Tags... > >", "structddc_1_1is__discrete__vector_3_01DiscreteVector_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_non_uniform_bsplines", "structddc_1_1is__non__uniform__bsplines.html", null ],
      [ "is_non_uniform_point_sampling", "structddc_1_1is__non__uniform__point__sampling.html", null ],
      [ "is_periodic_sampling", "structddc_1_1is__periodic__sampling.html", null ],
      [ "is_uniform_bsplines", "structddc_1_1is__uniform__bsplines.html", null ],
      [ "is_uniform_point_sampling", "structddc_1_1is__uniform__point__sampling.html", null ],
      [ "KnotDiscreteDimension", "namespaceddc.html#structddc_1_1KnotDiscreteDimension", "namespaceddc_structddc_1_1KnotDiscreteDimension_dup" ],
      [ "KnotsAsInterpolationPoints", "classddc_1_1KnotsAsInterpolationPoints.html", "classddc_1_1KnotsAsInterpolationPoints" ],
      [ "KokkosAllocator", "classddc_1_1KokkosAllocator.html", "classddc_1_1KokkosAllocator" ],
      [ "kwArgs_fft", "namespaceddc.html#structddc_1_1kwArgs__fft", "namespaceddc_structddc_1_1kwArgs__fft_dup" ],
      [ "NonUniformBSplines", "classddc_1_1NonUniformBSplines.html", "classddc_1_1NonUniformBSplines" ],
      [ "NonUniformBsplinesKnots", "structddc_1_1NonUniformBsplinesKnots.html", null ],
      [ "NonUniformPointSampling", "classddc_1_1NonUniformPointSampling.html", "classddc_1_1NonUniformPointSampling" ],
      [ "NullExtrapolationRule", "structddc_1_1NullExtrapolationRule.html", "structddc_1_1NullExtrapolationRule" ],
      [ "PdiEvent", "classddc_1_1PdiEvent.html", "classddc_1_1PdiEvent" ],
      [ "PeriodicExtrapolationRule", "structddc_1_1PeriodicExtrapolationRule.html", "structddc_1_1PeriodicExtrapolationRule" ],
      [ "PeriodicSampling", "classddc_1_1PeriodicSampling.html", "classddc_1_1PeriodicSampling" ],
      [ "ScopeGuard", "classddc_1_1ScopeGuard.html", "classddc_1_1ScopeGuard" ],
      [ "SplineBuilder", "classddc_1_1SplineBuilder.html", "classddc_1_1SplineBuilder" ],
      [ "SplineBuilder2D", "classddc_1_1SplineBuilder2D.html", "classddc_1_1SplineBuilder2D" ],
      [ "SplineEvaluator", "classddc_1_1SplineEvaluator.html", "classddc_1_1SplineEvaluator" ],
      [ "SplineEvaluator2D", "classddc_1_1SplineEvaluator2D.html", "classddc_1_1SplineEvaluator2D" ],
      [ "UniformBSplines", "classddc_1_1UniformBSplines.html", "classddc_1_1UniformBSplines" ],
      [ "UniformBsplinesKnots", "structddc_1_1UniformBsplinesKnots.html", null ],
      [ "UniformPointSampling", "classddc_1_1UniformPointSampling.html", "classddc_1_1UniformPointSampling" ]
    ] ]
];