var annotated =
[
    [ "reducer", "namespacereducer.html", [
      [ "sum", "structreducer_1_1sum.html", "structreducer_1_1sum" ],
      [ "prod", "structreducer_1_1prod.html", "structreducer_1_1prod" ],
      [ "land", "structreducer_1_1land.html", "structreducer_1_1land" ],
      [ "lor", "structreducer_1_1lor.html", "structreducer_1_1lor" ],
      [ "band", "structreducer_1_1band.html", "structreducer_1_1band" ],
      [ "bor", "structreducer_1_1bor.html", "structreducer_1_1bor" ],
      [ "bxor", "structreducer_1_1bxor.html", "structreducer_1_1bxor" ],
      [ "min", "structreducer_1_1min.html", "structreducer_1_1min" ],
      [ "max", "structreducer_1_1max.html", "structreducer_1_1max" ],
      [ "minmax", "structreducer_1_1minmax.html", "structreducer_1_1minmax" ]
    ] ],
    [ "AlignedAllocator", "classAlignedAllocator.html", "classAlignedAllocator" ],
    [ "Chunk", "namespace_3globalScope_4.html#classChunk", null ],
    [ "Chunk< ElementType, DiscreteDomain< DDims... >, Allocator >", "classChunk_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01Allocator_01_4.html", "classChunk_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01Allocator_01_4" ],
    [ "chunk_traits", "namespace_3globalScope_4.html#structchunk__traits", "namespace_3globalScope_4_structchunk__traits" ],
    [ "ChunkCommon", "namespace_3globalScope_4.html#classChunkCommon", null ],
    [ "ChunkCommon< ElementType, DiscreteDomain< DDims... >, LayoutStridedPolicy >", "classChunkCommon_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_01_4.html", "classChunkCommon_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_01_4" ],
    [ "ChunkSpan", "namespace_3globalScope_4.html#classChunkSpan", null ],
    [ "ChunkSpan< ElementType, DiscreteDomain< DDims... >, LayoutStridedPolicy, MemorySpace >", "classChunkSpan_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_00_01MemorySpace_01_4.html", "classChunkSpan_3_01ElementType_00_01DiscreteDomain_3_01DDims_8_8_8_01_4_00_01LayoutStridedPolicy_00_01MemorySpace_01_4" ],
    [ "ConversionOperators", "namespace_3globalScope_4.html#classConversionOperators", null ],
    [ "ConversionOperators< DiscreteVector< Tag > >", "classConversionOperators_3_01DiscreteVector_3_01Tag_01_4_01_4.html", "classConversionOperators_3_01DiscreteVector_3_01Tag_01_4_01_4" ],
    [ "DiscreteDomain", "classDiscreteDomain.html", "classDiscreteDomain" ],
    [ "DiscreteDomainIterator", "structDiscreteDomainIterator.html", "structDiscreteDomainIterator" ],
    [ "DiscreteElement", "classDiscreteElement.html", "classDiscreteElement" ],
    [ "DiscreteVector", "classDiscreteVector.html", "classDiscreteVector" ],
    [ "is_non_uniform_sampling", "structis__non__uniform__sampling.html", null ],
    [ "is_non_uniform_sampling< NonUniformPointSampling< CDim > >", "structis__non__uniform__sampling_3_01NonUniformPointSampling_3_01CDim_01_4_01_4.html", null ],
    [ "is_rectilinear_domain", "structis__rectilinear__domain.html", null ],
    [ "is_rectilinear_domain< DiscreteDomain< DDims... > >", "structis__rectilinear__domain_3_01DiscreteDomain_3_01DDims_8_8_8_01_4_01_4.html", null ],
    [ "is_uniform_domain", "structis__uniform__domain.html", null ],
    [ "is_uniform_domain< DiscreteDomain< DDims... > >", "structis__uniform__domain_3_01DiscreteDomain_3_01DDims_8_8_8_01_4_01_4.html", null ],
    [ "is_uniform_sampling", "structis__uniform__sampling.html", null ],
    [ "is_uniform_sampling< UniformPointSampling< CDim > >", "structis__uniform__sampling_3_01UniformPointSampling_3_01CDim_01_4_01_4.html", null ],
    [ "IsDiscreteElement", "structIsDiscreteElement.html", null ],
    [ "IsDiscreteElement< DiscreteElement< Tags... > >", "structIsDiscreteElement_3_01DiscreteElement_3_01Tags_8_8_8_01_4_01_4.html", null ],
    [ "IsDiscreteVector", "structIsDiscreteVector.html", null ],
    [ "IsDiscreteVector< DiscreteVector< Tags... > >", "structIsDiscreteVector_3_01DiscreteVector_3_01Tags_8_8_8_01_4_01_4.html", null ],
    [ "KokkosAllocator", "classKokkosAllocator.html", "classKokkosAllocator" ],
    [ "NonUniformPointSampling", "classNonUniformPointSampling.html", "classNonUniformPointSampling" ],
    [ "parallel_device_policy", "namespace_3globalScope_4.html#structparallel__device__policy", null ],
    [ "parallel_host_policy", "namespace_3globalScope_4.html#structparallel__host__policy", null ],
    [ "PdiEvent", "classPdiEvent.html", "classPdiEvent" ],
    [ "ScopeGuard", "classScopeGuard.html", "classScopeGuard" ],
    [ "serial_host_policy", "namespace_3globalScope_4.html#structserial__host__policy", null ],
    [ "UniformPointSampling", "classUniformPointSampling.html", "classUniformPointSampling" ]
];