var annotated_dup =
[
    [ "ddc", "namespaceddc.html", [
      [ "experimental", "namespaceddc_1_1experimental.html", [
        [ "Dims", "namespaceddc_1_1experimental.html#structddc_1_1experimental_1_1Dims", null ]
      ] ],
      [ "reducer", "namespaceddc_1_1reducer.html", [
        [ "band", "structddc_1_1reducer_1_1band.html", "structddc_1_1reducer_1_1band" ],
        [ "bor", "structddc_1_1reducer_1_1bor.html", "structddc_1_1reducer_1_1bor" ],
        [ "bxor", "structddc_1_1reducer_1_1bxor.html", "structddc_1_1reducer_1_1bxor" ],
        [ "land", "structddc_1_1reducer_1_1land.html", "structddc_1_1reducer_1_1land" ],
        [ "lor", "structddc_1_1reducer_1_1lor.html", "structddc_1_1reducer_1_1lor" ],
        [ "max", "structddc_1_1reducer_1_1max.html", "structddc_1_1reducer_1_1max" ],
        [ "min", "structddc_1_1reducer_1_1min.html", "structddc_1_1reducer_1_1min" ],
        [ "minmax", "structddc_1_1reducer_1_1minmax.html", "structddc_1_1reducer_1_1minmax" ],
        [ "prod", "structddc_1_1reducer_1_1prod.html", "structddc_1_1reducer_1_1prod" ],
        [ "sum", "structddc_1_1reducer_1_1sum.html", "structddc_1_1reducer_1_1sum" ]
      ] ],
      [ "AlignedAllocator", "classddc_1_1AlignedAllocator.html", "classddc_1_1AlignedAllocator" ],
      [ "Chunk", "classddc_1_1Chunk.html", "classddc_1_1Chunk" ],
      [ "chunk_traits", "namespaceddc.html#structddc_1_1chunk__traits", "namespaceddc_structddc_1_1chunk__traits_dup" ],
      [ "ChunkCommon", "classddc_1_1ChunkCommon.html", "classddc_1_1ChunkCommon" ],
      [ "ChunkSpan", "classddc_1_1ChunkSpan.html", "classddc_1_1ChunkSpan" ],
      [ "ConstantExtrapolationRule", "structddc_1_1ConstantExtrapolationRule.html", "structddc_1_1ConstantExtrapolationRule" ],
      [ "coordinate_of", "namespaceddc.html#structddc_1_1coordinate__of", "namespaceddc_structddc_1_1coordinate__of_dup" ],
      [ "Deriv", "structddc_1_1Deriv.html", null ],
      [ "DiscreteDimension", "structddc_1_1DiscreteDimension.html", null ],
      [ "DiscreteDomain", "classddc_1_1DiscreteDomain.html", "classddc_1_1DiscreteDomain" ],
      [ "DiscreteDomain<>", "classddc_1_1DiscreteDomain_3_4.html", "classddc_1_1DiscreteDomain_3_4" ],
      [ "DiscreteDomainIterator", "structddc_1_1DiscreteDomainIterator.html", "structddc_1_1DiscreteDomainIterator" ],
      [ "DiscreteElement", "classddc_1_1DiscreteElement.html", "classddc_1_1DiscreteElement" ],
      [ "DiscreteVector", "classddc_1_1DiscreteVector.html", "classddc_1_1DiscreteVector" ],
      [ "Fourier", "namespaceddc.html#structddc_1_1Fourier", null ],
      [ "GrevilleInterpolationPoints", "classddc_1_1GrevilleInterpolationPoints.html", "classddc_1_1GrevilleInterpolationPoints" ],
      [ "is_discrete_domain", "structddc_1_1is__discrete__domain.html", null ],
      [ "is_discrete_domain< DiscreteDomain< Tags... > >", "structddc_1_1is__discrete__domain_3_01DiscreteDomain_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_discrete_element", "structddc_1_1is__discrete__element.html", null ],
      [ "is_discrete_element< DiscreteElement< Tags... > >", "structddc_1_1is__discrete__element_3_01DiscreteElement_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_discrete_vector", "structddc_1_1is__discrete__vector.html", null ],
      [ "is_discrete_vector< DiscreteVector< Tags... > >", "structddc_1_1is__discrete__vector_3_01DiscreteVector_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_evaluator_admissible", "structddc_1_1is__evaluator__admissible.html", null ],
      [ "is_evaluator_admissible< SplineBuilder2D< ExecSpace, MemorySpace, BSplines1, BSplines2, DDimI1, DDimI2, SBCLower1, SBCUpper1, SBCLower2, SBCUpper2, Solver >, SplineEvaluator2D< ExecSpace, MemorySpace, BSplines1, BSplines2, DDimI1, DDimI2, LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2 > >", "structddc_1_1is__evaluator__admissible_3_01SplineBuilder2D_3_01ExecSpace_00_01MemorySpace_00_01B5ddee331a52e77ca5c7235354cad196d.html", null ],
      [ "is_evaluator_admissible< SplineBuilder2D< ExecSpace, MemorySpace, BSplines1, BSplines2, DDimI1, DDimI2, SBCLower1, SBCUpper1, SBCLower2, SBCUpper2, Solver >, SplineEvaluatorND< ExecSpace, MemorySpace, TypeSeq< BSplines1, BSplines2 >, TypeSeq< DDimI1, DDimI2 >, TypeSeq< LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2 > > >", "structddc_1_1is__evaluator__admissible_3_01SplineBuilder2D_3_01ExecSpace_00_01MemorySpace_00_01B747c8d625bfc61c3b3709f356343a878.html", null ],
      [ "is_evaluator_admissible< SplineBuilder3D< ExecSpace, MemorySpace, BSplines1, BSplines2, BSplines3, DDimI1, DDimI2, DDimI3, SBCLower1, SBCUpper1, SBCLower2, SBCUpper2, SBCLower3, SBCUpper3, Solver >, SplineEvaluator3D< ExecSpace, MemorySpace, BSplines1, BSplines2, BSplines3, DDimI1, DDimI2, DDimI3, LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2, LowerExtrapolationRule3, UpperExtrapolationRule3 > >", "structddc_1_1is__evaluator__admissible_3_01SplineBuilder3D_3_01ExecSpace_00_01MemorySpace_00_01Bac9e23e7f6fbd4d1966a1b81047cadfa.html", null ],
      [ "is_evaluator_admissible< SplineBuilder3D< ExecSpace, MemorySpace, BSplines1, BSplines2, BSplines3, DDimI1, DDimI2, DDimI3, SBCLower1, SBCUpper1, SBCLower2, SBCUpper2, SBCLower3, SBCUpper3, Solver >, SplineEvaluatorND< ExecSpace, MemorySpace, TypeSeq< BSplines1, BSplines2, BSplines3 >, TypeSeq< DDimI1, DDimI2, DDimI3 >, TypeSeq< LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2, LowerExtrapolationRule3, UpperExtrapolationRule3 > > >", "structddc_1_1is__evaluator__admissible_3_01SplineBuilder3D_3_01ExecSpace_00_01MemorySpace_00_01B0179051434d9cc597c54bac79b563c68.html", null ],
      [ "is_evaluator_admissible< SplineBuilder< ExecSpace, MemorySpace, BSplines, DDim, SBCLower, SBCUpper, Solver >, SplineEvaluator< ExecSpace, MemorySpace, BSplines, DDim, LowerExtrapolationRule, UpperExtrapolationRule > >", "structddc_1_1is__evaluator__admissible_3_01SplineBuilder_3_01ExecSpace_00_01MemorySpace_00_01BSp6aaca04ffe396595a3d1153bacce2f4d.html", null ],
      [ "is_evaluator_admissible< SplineBuilder< ExecSpace, MemorySpace, BSplines, DDim, SBCLower, SBCUpper, Solver >, SplineEvaluatorND< ExecSpace, MemorySpace, TypeSeq< BSplines >, TypeSeq< DDim >, TypeSeq< LowerExtrapolationRule, UpperExtrapolationRule > > >", "structddc_1_1is__evaluator__admissible_3_01SplineBuilder_3_01ExecSpace_00_01MemorySpace_00_01BSp30b33745d003ff962d3ce398690d6a53.html", null ],
      [ "is_non_uniform_bsplines", "structddc_1_1is__non__uniform__bsplines.html", null ],
      [ "is_non_uniform_point_sampling", "structddc_1_1is__non__uniform__point__sampling.html", null ],
      [ "is_periodic_sampling", "structddc_1_1is__periodic__sampling.html", null ],
      [ "is_sparse_discrete_domain", "structddc_1_1is__sparse__discrete__domain.html", null ],
      [ "is_sparse_discrete_domain< SparseDiscreteDomain< Tags... > >", "structddc_1_1is__sparse__discrete__domain_3_01SparseDiscreteDomain_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_spline_builder", "structddc_1_1is__spline__builder.html", null ],
      [ "is_spline_builder2d", "structddc_1_1is__spline__builder2d.html", null ],
      [ "is_spline_builder2d< SplineBuilder2D< ExecSpace, MemorySpace, BSpline1, BSpline2, DDimI1, DDimI2, SBCLower1, SBCUpper1, SBCLower2, SBCUpper2, Solver > >", "structddc_1_1is__spline__builder2d_3_01SplineBuilder2D_3_01ExecSpace_00_01MemorySpace_00_01BSpli4225ea179f2e6753dc817ecd501c0002.html", null ],
      [ "is_spline_builder3d", "structddc_1_1is__spline__builder3d.html", null ],
      [ "is_spline_builder3d< SplineBuilder3D< ExecSpace, MemorySpace, BSpline1, BSpline2, BSpline3, DDimI1, DDimI2, DDimI3, SBCLower1, SBCUpper1, SBCLower2, SBCUpper2, SBCLower3, SBCUpper3, Solver > >", "structddc_1_1is__spline__builder3d_3_01SplineBuilder3D_3_01ExecSpace_00_01MemorySpace_00_01BSplic774c2a73c5b6ee20dd5693160b374fe.html", null ],
      [ "is_spline_builder< SplineBuilder< ExecSpace, MemorySpace, BSplines, InterpolationDDim, SBCLower, SBCUpper, Solver > >", "structddc_1_1is__spline__builder_3_01SplineBuilder_3_01ExecSpace_00_01MemorySpace_00_01BSplines_9552635f9929289f9d3a89cd5466ddf1.html", null ],
      [ "is_spline_evaluator", "structddc_1_1is__spline__evaluator.html", null ],
      [ "is_spline_evaluator2d", "structddc_1_1is__spline__evaluator2d.html", null ],
      [ "is_spline_evaluator2d< SplineEvaluator2D< ExecSpace, MemorySpace, BSpline1, BSpline2, EvaluationDDim1, EvaluationDDim2, LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2 > >", "structddc_1_1is__spline__evaluator2d_3_01SplineEvaluator2D_3_01ExecSpace_00_01MemorySpace_00_01Bab426b7c2afbbe95ee03abe88c8cadbb.html", null ],
      [ "is_spline_evaluator2d< SplineEvaluatorND< ExecSpace, MemorySpace, ddc::TypeSeq< BSpline1, BSpline2 >, ddc::TypeSeq< EvaluationDDim1, EvaluationDDim2 >, ddc::TypeSeq< LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2 > > >", "structddc_1_1is__spline__evaluator2d_3_01SplineEvaluatorND_3_01ExecSpace_00_01MemorySpace_00_01dd01bf355e5018f2b391d6d2cbcd7e580.html", null ],
      [ "is_spline_evaluator3d", "structddc_1_1is__spline__evaluator3d.html", null ],
      [ "is_spline_evaluator3d< SplineEvaluator3D< ExecSpace, MemorySpace, BSpline1, BSpline2, BSpline3, EvaluationDDim1, EvaluationDDim2, EvaluationDDim3, LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2, LowerExtrapolationRule3, UpperExtrapolationRule3 > >", "structddc_1_1is__spline__evaluator3d_3_01SplineEvaluator3D_3_01ExecSpace_00_01MemorySpace_00_01B9e5b449864924bda800a9c75687db942.html", null ],
      [ "is_spline_evaluator3d< SplineEvaluatorND< ExecSpace, MemorySpace, ddc::TypeSeq< BSpline1, BSpline2, BSpline3 >, ddc::TypeSeq< EvaluationDDim1, EvaluationDDim2, EvaluationDDim3 >, ddc::TypeSeq< LowerExtrapolationRule1, UpperExtrapolationRule1, LowerExtrapolationRule2, UpperExtrapolationRule2, LowerExtrapolationRule3, UpperExtrapolationRule3 > > >", "structddc_1_1is__spline__evaluator3d_3_01SplineEvaluatorND_3_01ExecSpace_00_01MemorySpace_00_01dd81365fb06dc245f058d487b4c12e6bc.html", null ],
      [ "is_spline_evaluator< SplineEvaluator< ExecSpace, MemorySpace, BSplines, EvaluationDDim, LowerExtrapolationRule, UpperExtrapolationRule > >", "structddc_1_1is__spline__evaluator_3_01SplineEvaluator_3_01ExecSpace_00_01MemorySpace_00_01BSpli9c02ad999c3c97f462f5c25d3036992e.html", null ],
      [ "is_spline_evaluator< SplineEvaluatorND< ExecSpace, MemorySpace, ddc::TypeSeq< BSplines >, ddc::TypeSeq< EvaluationDDim >, ddc::TypeSeq< LowerExtrapolationRule, UpperExtrapolationRule > > >", "structddc_1_1is__spline__evaluator_3_01SplineEvaluatorND_3_01ExecSpace_00_01MemorySpace_00_01ddcfb5d1f6095588f4584a317e06bb4532f.html", null ],
      [ "is_spline_evaluatornd", "structddc_1_1is__spline__evaluatornd.html", null ],
      [ "is_spline_evaluatornd< SplineEvaluatorND< ExecSpace, MemorySpace, BSplines, EvaluationDDim, ExtrapolationRule > >", "structddc_1_1is__spline__evaluatornd_3_01SplineEvaluatorND_3_01ExecSpace_00_01MemorySpace_00_01B1d0e8c8d860ae3fbb7f6a0033b7ac03a.html", null ],
      [ "is_strided_discrete_domain", "structddc_1_1is__strided__discrete__domain.html", null ],
      [ "is_strided_discrete_domain< StridedDiscreteDomain< Tags... > >", "structddc_1_1is__strided__discrete__domain_3_01StridedDiscreteDomain_3_01Tags_8_8_8_01_4_01_4.html", null ],
      [ "is_uniform_bsplines", "structddc_1_1is__uniform__bsplines.html", null ],
      [ "is_uniform_point_sampling", "structddc_1_1is__uniform__point__sampling.html", null ],
      [ "KnotDiscreteDimension", "namespaceddc.html#structddc_1_1KnotDiscreteDimension", "namespaceddc_structddc_1_1KnotDiscreteDimension_dup" ],
      [ "KnotsAsInterpolationPoints", "classddc_1_1KnotsAsInterpolationPoints.html", "classddc_1_1KnotsAsInterpolationPoints" ],
      [ "KokkosAllocator", "classddc_1_1KokkosAllocator.html", "classddc_1_1KokkosAllocator" ],
      [ "kwArgs_fft", "namespaceddc.html#structddc_1_1kwArgs__fft", "namespaceddc_structddc_1_1kwArgs__fft_dup" ],
      [ "NonUniformBSplines", "classddc_1_1NonUniformBSplines.html", "classddc_1_1NonUniformBSplines" ],
      [ "NonUniformBsplinesKnots", "structddc_1_1NonUniformBsplinesKnots.html", null ],
      [ "NonUniformPointSampling", "classddc_1_1NonUniformPointSampling.html", "classddc_1_1NonUniformPointSampling" ],
      [ "NullExtrapolationRule", "structddc_1_1NullExtrapolationRule.html", "structddc_1_1NullExtrapolationRule" ],
      [ "PdiEvent", "classddc_1_1PdiEvent.html", "classddc_1_1PdiEvent" ],
      [ "PeriodicExtrapolationRule", "structddc_1_1PeriodicExtrapolationRule.html", "structddc_1_1PeriodicExtrapolationRule" ],
      [ "PeriodicSampling", "classddc_1_1PeriodicSampling.html", "classddc_1_1PeriodicSampling" ],
      [ "PrinterOptions", "structddc_1_1PrinterOptions.html", "structddc_1_1PrinterOptions" ],
      [ "ScopeGuard", "classddc_1_1ScopeGuard.html", "classddc_1_1ScopeGuard" ],
      [ "SparseDiscreteDomain", "classddc_1_1SparseDiscreteDomain.html", "classddc_1_1SparseDiscreteDomain" ],
      [ "SparseDiscreteDomain<>", "classddc_1_1SparseDiscreteDomain_3_4.html", "classddc_1_1SparseDiscreteDomain_3_4" ],
      [ "SplineBuilder", "classddc_1_1SplineBuilder.html", "classddc_1_1SplineBuilder" ],
      [ "SplineBuilder2D", "classddc_1_1SplineBuilder2D.html", "classddc_1_1SplineBuilder2D" ],
      [ "SplineBuilder3D", "classddc_1_1SplineBuilder3D.html", "classddc_1_1SplineBuilder3D" ],
      [ "SplineEvaluator", "classddc_1_1SplineEvaluator.html", "classddc_1_1SplineEvaluator" ],
      [ "SplineEvaluator2D", "classddc_1_1SplineEvaluator2D.html", "classddc_1_1SplineEvaluator2D" ],
      [ "SplineEvaluator3D", "classddc_1_1SplineEvaluator3D.html", "classddc_1_1SplineEvaluator3D" ],
      [ "SplineEvaluatorND", "namespaceddc.html#classddc_1_1SplineEvaluatorND", null ],
      [ "SplineEvaluatorND< ExecSpace, MemorySpace, TypeSeq< BSplines... >, TypeSeq< EvaluationDDim... >, TypeSeq< ExtrapolationRule... > >", "classddc_1_1SplineEvaluatorND_3_01ExecSpace_00_01MemorySpace_00_01TypeSeq_3_01BSplines_8_8_8_01_f833e29ba3ac0ee5ee9bb80710900f22.html", "classddc_1_1SplineEvaluatorND_3_01ExecSpace_00_01MemorySpace_00_01TypeSeq_3_01BSplines_8_8_8_01_f833e29ba3ac0ee5ee9bb80710900f22" ],
      [ "StridedDiscreteDomain", "classddc_1_1StridedDiscreteDomain.html", "classddc_1_1StridedDiscreteDomain" ],
      [ "StridedDiscreteDomain<>", "classddc_1_1StridedDiscreteDomain_3_4.html", "classddc_1_1StridedDiscreteDomain_3_4" ],
      [ "StridedDiscreteDomainIterator", "structddc_1_1StridedDiscreteDomainIterator.html", "structddc_1_1StridedDiscreteDomainIterator" ],
      [ "TypeSeq", "namespaceddc.html#structddc_1_1TypeSeq", null ],
      [ "UniformBSplines", "classddc_1_1UniformBSplines.html", "classddc_1_1UniformBSplines" ],
      [ "UniformBsplinesKnots", "structddc_1_1UniformBsplinesKnots.html", null ],
      [ "UniformPointSampling", "classddc_1_1UniformPointSampling.html", "classddc_1_1UniformPointSampling" ]
    ] ]
];