# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

---
coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit
    patch:
      default:
        target: 100%
