# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

---
spack:
  concretizer:
    reuse: false
    unify: true
  packages:
    all:
      require:
        - 'target=x86_64'
        - '~cuda'
        - '~rocm'
        - '~openmp'
        - '~mpi'
        - '~fortran'
    c:
      require: 'gcc@11'
    cxx:
      require: 'gcc@11'
    fortran:
      require: 'gcc@11'
    lapack:
      require: 'openblas@0.3'
  repos:
    builtin:
      tag: v2026.03.0
  specs:
    - 'gcc@11'
    - 'benchmark@1.9 ~performance_counters'
    - 'cmake@3.25'
    - 'ginkgo@1.8'
    - 'googletest@1.14 +gmock'
    - 'kokkos@4.7'
    - 'kokkos-fft@0.3 host_backend=fftw-serial'
    - 'kokkos-kernels@4.7'
    - 'lapack'
    - 'paraconf@1.0'
    - 'pkgconfig'
    - 'pdi@1.10.1:1.10'
    - 'pdiplugin-decl-hdf5@1.10.1:1.10'
    - 'pdiplugin-user-code@1.10.1:1.10'
    - 'pdiplugin-trace@1.10.1:1.10'
    - 'py-numpy@1.24'
    - 'py-pytest@8.4'
  view:
    default:
      root: .spack-env/view
      exclude: ['gcc-runtime']
