# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

---
name: CMake checks

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '.github/workflows/cmake-checks.yml'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.cmake.in'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cmake-checks.yml'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.cmake.in'
  workflow_dispatch:

jobs:
  cmake-format:
    name: CMake format check using gersemi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gersemi
        run: pipx install gersemi~=0.19
      - name: Run gersemi
        run: |
          gersemi --check $(git ls-files '*.cmake' ':!cmake/DDCCheckRequiredKokkosOptions.cmake' ':!cmake/FindLAPACKE.cmake')
          gersemi --check $(git ls-files 'CMakeLists.txt' '*/CMakeLists.txt')
