# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

name: gyselalibxx
on: workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gyselalibxx
      uses: actions/checkout@v4
      with:
        repository: gyselax/gyselalibxx
        submodules: recursive
    - name: rm ddc
      run: rm -rf vendor/ddc
    - name: Checkout ddc
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: vendor/ddc
    - name: Build
      run: |
        cat<<-EOF > run.sh
          set -xe
          git config --global --add safe.directory /src/vendor/kokkos
          cmake -DCMAKE_CXX_FLAGS=-Wall -DBUILD_BENCHMARKS=ON -B build -S /src
          cmake --build build --parallel 2 --verbose
          ctest --test-dir build --output-on-failure --timeout 5 -LE test_on_Release_only
        EOF
        docker run -v ${PWD}:/src:ro ghcr.io/gyselax/voicexx_env bash /src/run.sh
      continue-on-error: true
  tests_Release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gyselalibxx
      uses: actions/checkout@v4
      with:
        repository: gyselax/gyselalibxx
        submodules: recursive
    - name: rm ddc
      run: rm -rf vendor/ddc
    - name: Checkout ddc
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: vendor/ddc
    - name: Build
      run: |
        cat<<-EOF > run.sh
          set -xe
          git config --global --add safe.directory /src/vendor/kokkos
          cmake -DCMAKE_CXX_FLAGS=-Wall -DBUILD_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=Release -B build -S /src
          cmake --build build --parallel 2 --verbose
          ctest --test-dir build --output-on-failure --timeout 5
        EOF
        docker run -v ${PWD}:/src:ro ghcr.io/gyselax/voicexx_env bash /src/run.sh
      continue-on-error: true
