# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

---
name: Markdown checks

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '.github/workflows/markdown-checks.yaml'
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/markdown-checks.yaml'
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown lint using markdownlint-cli2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: DavidAnson/markdownlint-cli2-action@8de2aa07cae85fd17c0b35642db70cf5495f1d25  # v24.0.0
        with:
          globs: |
            AUTHORS
            '**/*.{md,markdown}'
