# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

---
name: Shell checks

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '.github/workflows/shell-checks.yaml'
      - '**.sh'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shell-lint:
    name: Shell lint using shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38  # 2.0.0
        env:
          SHELLCHECK_OPTS: -e SC1091
