# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

---
name: Tests on macOS

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '.github/workflows/tests-macos.yaml'
      - '**.cpp'
      - '**.hpp'
      - '**.hpp.in'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.cmake.in'
      - 'vendor/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tests-macos.yaml'
      - '**.cpp'
      - '**.hpp'
      - '**.hpp.in'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.cmake.in'
      - 'vendor/**'

concurrency:
  group: ${{github.workflow}}-${{github.ref == github.ref_protected && github.run_id || github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-macos:
    if: github.ref_name != 'main'
    strategy:
      fail-fast: false
      matrix:
        backend:
          - name: 'cpu'
            c_compiler: 'clang'
            cxx_compiler: 'clang++'
            ddc_extra_cxx_flags: '-Wextra-semi -Wextra-semi-stmt -Wold-style-cast'
        cxx_version: ['20', '23']
        cmake_build_type: ['Debug', 'Release']
        os: [macos-14, macos-15]
    runs-on: ${{matrix.os}}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CMAKE_BUILD_TYPE: ${{matrix.cmake_build_type}}
      DDC_ROOT: ${{github.workspace}}/opt/ddc
    permissions:
      packages: write  # Required to push to registry
    steps:
      - name: Checkout built branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Set up Spack
        uses: spack/setup-spack@16b756799ede8b28951287f89bcd3fdb32ec1ca3  # v3.0.0
        with:
          spack_ref: v1.1.1
          buildcache: true
      - name: Install
        shell: spack-bash {0}
        run: |
          spack env create . spack-env/spack-${{matrix.os}}.yaml
          spack --env . repo update
          spack --env . install
      - name: Push packages and update index
        shell: spack-bash {0}
        env:
          GITHUB_USER: ${{github.actor}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: spack --env . buildcache push --update-index local-buildcache
        if: ${{!cancelled()}}
      - name: Build DDC
        shell: spack-bash {0}
        run: |
          spack env activate .
          cmake \
            -D CMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wno-sign-compare -pedantic-errors ${{matrix.backend.ddc_extra_cxx_flags}}" \
            -D CMAKE_CXX_STANDARD=${{matrix.cxx_version}} \
            -D DDC_BUILD_BENCHMARKS=ON \
            -B build
          cmake --build build
      - name: Run unit tests
        shell: spack-bash {0}
        run: |
          spack env activate .
          ctest --test-dir build --output-on-failure --timeout 25 --output-junit tests.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@3a81627bfac62268172037048872e8ebd4207e6d  # v6.4.1
        if: ( success() || failure() )  # always run even if the previous step fails
        with:
          annotate_only: true  # forked repo cannot write to checks so just do annotations
          report_paths: '${{github.workspace}}/build/tests.xml'
      - name: Install DDC
        shell: spack-bash {0}
        run: |
          spack env activate .
          cmake --install build --prefix $DDC_ROOT
          rm -rf build
      - name: Run install tests
        shell: spack-bash {0}
        run: |
          spack env activate .
          cmake \
            -B build \
            -S ./install_test
          cmake --build build
