# Copyright (C) The DDC development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT

---
name: Tests on Ubuntu

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '.github/workflows/tests-ubuntu.yaml'
      - '.clang-tidy'
      - '**.cpp'
      - '**.hpp'
      - '**.hpp.in'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.cmake.in'
      - 'docker/**'
      - 'vendor/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/tests-ubuntu.yaml'
      - '.clang-tidy'
      - '**.cpp'
      - '**.hpp'
      - '**.hpp.in'
      - 'CMakeLists.txt'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - '**.cmake.in'
      - 'docker/**'
      - 'vendor/**'

concurrency:
  group: ${{github.workflow}}-${{github.ref == github.ref_protected && github.run_id || github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-spack-env:
    runs-on: ubuntu-26.04
    permissions:
      packages: write  # Required to push to registry
    steps:
      - name: Checkout built branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Spack
        uses: spack/setup-spack@16b756799ede8b28951287f89bcd3fdb32ec1ca3  # v3.0.0
        with:
          spack_ref: v1.2.2
          buildcache: true
      - name: Install
        shell: spack-bash {0}
        run: |
          spack env create . spack-env/dev-ddc.yaml
          spack --env . repo update
          spack --env . install
      - name: Install
        shell: spack-bash {0}
        run: |
          spack env activate .
          cmake -D CMAKE_VERIFY_INTERFACE_HEADER_SETS=ON -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -D DDC_BUILD_EXAMPLES=OFF -D DDC_BUILD_KERNELS_FFT=OFF -D DDC_BUILD_KERNELS_SPLINES=OFF -D DDC_BUILD_PDI_WRAPPER=OFF -B build
      - name: Download Template coverage
        run: |
          wget https://github.com/petiaccja/TemplateCoverage/releases/download/v1.4.0/TemplateCoverage_Linux_x86_64.zip
          unzip TemplateCoverage_Linux_x86_64.zip
          chmod +x ./TemplateCoverage_Linux_x86_64/template-coverage
      - name: Template coverage
        shell: spack-bash {0}
        run: |
          spack env activate .
          export RESOURCE_DIR=$(clang++ -print-resource-dir)
          python3 ./TemplateCoverage_Linux_x86_64/run_on_compile_commands.py -p build/compile_commands.json TemplateCoverage_Linux_x86_64/template-coverage -- --format=lcov --out-file=template_coverage.lcov -extra-arg=-resource-dir=$RESOURCE_DIR
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          disable_search: true
          files: template_coverage.lcov
